### ISSUE TITLE
how to put leaky_relu activation in MLP ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#10]
Hi, 

I have a question: how to set "leaky_relu" instead of relu as MLP activation function ?

![image](https://user-images.githubusercontent.com/1186658/123210627-8da3d380-d4c2-11eb-9654-4e05e4f6ee1f.png)

that would be interesting to test.

Also how can I introduce layernorm in the MLP ?

**Comment by PatReis** [comment]
If kgcnn.ops.activ is loaded (should happen in principle in all modules, or i will put it in __init__.py) you can simply us
"kgcnn>leaky_relu" or if you want to specify you can use directly kgcnn.ops.activ.leaky_relu(alpha=0.2) or if you want to stay with the serialized version, you can use {'class_name': 'kgcnn>leaky_relu', "config": {'trainable': False, 'dtype': 'float32', 'alpha': 0.2}}

**Comment by thegodone** [comment]
thanks for explanation, very useful.

I try really to compare the two codes Keras/PyG so it can work to "swish" too.

**Comment by PatReis** [comment]
I think keras has "swish" but we have a "kgcnn>swish" too (which requires more memory but we could extend for arbitrary exponent).

**Comment by PatReis** [comment]
I updated the activation functions to also allow learnable parameters for leaky_relu and swish, but that is not usually done, as far as I can tell. I close this now, but you can re-open if you something does not work as expected.
