### ISSUE TITLE
How to add compute_partial_charges into list of node features ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#101]
I try this and did not see the partial_charges in my dataset after running this call ?
```
        dataset.set_attributes(add_hydrogen=False,has_conformers=is3D, 
                               compute_partial_charges= 'gasteiger')
```

1 - how to get the charges in the dataset ?
2- how to generalise with more descriptors similar of this one ?

**Comment by PatReis** [comment]
1.) I hoped that I could save the partial charges in the SDF file format with RDKit, but I was not able to do so yet. This would be the most elegant and clean way to do it. So at the moment they are computed on reading the dataset into memory.
2.) You can simply add the partial charges into your feature vector with the "GasteigerCharge" or "GasteigerHCharge" keys.
If you want them separately to attributes you can use a custom callback:

```python
dataset.set_attributes(additional_callbacks={'GasteigerCharge': lambda mg, ds: np.array(mg.node_attributes(["GasteigerCharge"], encoder={}), dtype='float') })
```

**Comment by thegodone** [comment]
How to extend the feature vector than from the default one ?
- is it like [*defaultFeature, "GasteigerCharge", "TADADA", "BLABLA",etc ] ?
and where to define it in the hyper model parameter of can I do it dynamically cause today my OCHEM code is like this ?
 dataset = MoleculeNetDataset(file_name=name, data_directory="", dataset_name="MoleculeNetDataset")
        
        dataset.prepare_data(overwrite=overwrite, smiles_column_name="smiles",
                             make_conformers=is3D, add_hydrogen=is3D,
                             optimize_conformer=is3D, num_workers=10)

        dataset.read_in_memory(label_column_name=cols, add_hydrogen=False,
                               has_conformers=False)
                               
        dataset.set_attributes(add_hydrogen=False,has_conformers=is3D, 
                               compute_partial_charges= 'gasteiger')

**Comment by thegodone** [comment]
set_attributes has no parameter for node_attributes ?

**Comment by PatReis** [comment]
Ah sorry, yes, it is `nodes = ['Symbol', 'TotalDegree', 'FormalCharge', 'NumRadicalElectrons', 'Hybridization',
'IsAromatic', 'IsInRing', 'TotalNumHs', 'CIPCode', "ChiralityPossible", "ChiralTag"]`

then you can simply add "GasteigerCharge" in the list. You do not need an encoder as it is already of type float.

Or you can set `nodes = MoleculeNetDataset._default_node_attributes + ["GasteigerCharge"]`

**Comment by thegodone** [comment]
It works in principle but since I compute it twice (I still don't know why), I cannot see the results in the final dataset.

I guess the memory is flash (specially because this is atom objects properties, if you regenerate the molecule from sdk thant the values are gone so you need to rerun it in the second loop...)

**Comment by thegodone** [comment]
did you try this to store in sdf the partial charge ?
```
m = Chem.MolFromSmiles('CO')
m.GetAtomWithIdx(0).SetDoubleProp('_foo',3.14)
m.GetAtomWithIdx(1).SetDoubleProp('_foo',0.14)
Chem.CreateAtomDoublePropertyList(m,'_foo')
print(m.GetProp('atom.dprop._foo'))
from io import StringIO
sio = StringIO()
w = Chem.SDWriter(sio)
w.write(m)
w=None
print(sio.getvalue())   
```
result:
3.1400000000000001 0.14000000000000001

     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
M  END
>  <atom.dprop._foo>  (1) 
3.1400000000000001 0.14000000000000001

$$$$

**Comment by thegodone** [comment]
```
smis = ['C'*i for i in range(1,20)]
smis
mols = [ Chem.MolFromSmiles(s) for s in smis]


from rdkit.Chem import AllChem
for mol in mols:
    AllChem.ComputeGasteigerCharges(mol)
    Chem.CreateAtomDoublePropertyList(mol,'_GasteigerCharge')


w = Chem.SDWriter("molecules.sdf")
for m in mols:
    w.write(m)
w.close()

r = Chem.SDMolSupplier("molecules.sdf")
for m in r:
    print(m.GetProp('atom.dprop._GasteigerCharge'))
r.reset()
```

**Comment by thegodone** [comment]
I finally find the bug

this line erase the "extended atomic feature" _GasteigerCharge:
dataset.set_methods(hyper["data"]["dataset"]["methods"])
        
If I remove it, I have only two loops and not three and the _GasteigerCharge is retain.

**Comment by PatReis** [comment]
Oh, yes, if you call `set_attributes` method in the `set_methods` list then they are overwritten. But you could add your information for attributes there as well. The `read_in_memory` actually uses the `set_attributes` function, or in fact for `MoleculeNetDataset` they are exactly the same. 

Thanks for the code example. I will have a look at it and add it to the pre-processing if I find a way to make it work for OpenBabel too.

**Comment by thegodone** [comment]
there is another alternative to save pickle molecule here a small example:
´´´
m = Chem.MolFromSmiles('CCOC')
from rdkit.Chem import rdPartialCharges
rdPartialCharges.ComputeGasteigerCharges(m)
print(m.GetAtomWithIdx(0).GetPropsAsDict())

pkl = m.ToBinary(Chem.PropertyPickleOptions.AllProps)
nm =  Chem.Mol(pkl)
print(nm.GetAtomWithIdx(0).GetPropsAsDict())
````

result:

{'__computedProps': <rdkit.rdBase._vectNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE object at 0x16bbe25c0>, '_CIPRank': 0, '_GasteigerCharge': -0.04157928663851465, '_GasteigerHCharge': 0.0761476420745963}
{'__computedProps': <rdkit.rdBase._vectNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE object at 0x16bbe25c0>, '_CIPRank': 0, '_GasteigerCharge': -0.04157928663851465, '_GasteigerHCharge': 0.0761476420745963}
