### ISSUE TITLE
adding min best rmse for molecules regressions targets

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#108]
Based on lot of paper earlystopping is a good choice for stop model before overfitting. I would love that you add the min best scoring in the training results evaluation cause this is clearly a good practice to select model.

**Comment by PatReis** [comment]
We already have this option. I will add a second README_min_max.md along with the main README.md which should be displayed on the github page.

**Comment by thegodone** [comment]
thanks
