### ISSUE TITLE
Using DimeNetPP implementation

### ISSUE THREAD

**Issue by knc6** [aimat-lab/gcnn_keras#110]
Thank you for developing such a useful package.

We have been working on developing a JARVIS-leaderboard project for benchmarking and we would like to add kgcnn results.

We were able to add kgcnn-SchNet model on the leaderboard (benchmarks [here](https://github.com/usnistgov/jarvis_leaderboard/tree/main/jarvis_leaderboard/benchmarks/kgcnn_schnet), webpage example [here](https://pages.nist.gov/jarvis_leaderboard/AI/SinglePropertyPrediction/dft_3d_formation_energy_peratom/), colab notebook [here](https://colab.research.google.com/github/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/kgcnn_jarvis_leaderboard.ipynb)).

But, while using the DimeNetPP, encountered an error: `TypeError: dispatcher for __array_function__ did not return an iterable`
The DimeNetPP notebook is kept [here](https://github.com/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/kgcnn_jarvis_leaderboard_dimenetPP.ipynb).

I may be missing something here. Please let me know.

**Comment by PatReis** [comment]
Hallo,
thanks, that sounds great.
As far as I can see, DimeNetPP requires angles as input. You likely have to add them to the dataset after the multi-edges like so:

```python
dataset.map_list(method="set_range_periodic", max_distance=5.0, max_neighbours=20)
dataset.map_list(method="set_angle", allow_multi_edges=True)
```
Which should apply the Graph preprocessor `kgcnn.graph.preprocessor.SetAngle` to each graph.

**Comment by knc6** [comment]
[That](https://github.com/usnistgov/jarvis_leaderboard/tree/main/jarvis_leaderboard/contributions/kgcnn_dimenetPP) worked.
