### ISSUE TITLE
cannot run examples anymore

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#12]
I test Lipop this morning and got an issue in the printer log:
![image](https://user-images.githubusercontent.com/1186658/123386937-7aaf0300-d597-11eb-8f80-7a9ac224566d.png)

any idea what is wrong ?

I have tf 2.3.1 / py 3.7.10

**Comment by PatReis** [comment]
Okay, it should work with latest commit. I changed the reset_states() method to reset_state() for tf 2.5 and removed the old one (which caused the problem). I keep now both, which seems to work in both 2.3 and 2.5.

**Comment by thegodone** [comment]
thanks working now on ft 2.3

Le ven. 25 juin 2021 à 10:53, Patrick Reiser ***@***.***> a
écrit :
