### ISSUE TITLE
SOTA Graphs

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#19]
### Discussed in https://github.com/aimat-lab/gcnn_keras/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **thegodone** June 30, 2021</sup>
- [x] - AttentiveFP
- [x] - Dimenet++
- [x] - GAT
- [x] - GATv2
- [x] - GIN
- [x] - PAiNN
- [x] - GATv2 autoencoder</di>

**Comment by PatReis** [comment]
I added Gatv2, will do PAiNN next

**Comment by thegodone** [comment]
I have an example of PAiNN that I will send you tomorrow. can you give me your email ?

**Comment by PatReis** [comment]
Sure. I was just about to start with PAiNN. My e-mail is: patrick.reiser@kit.edu
