### ISSUE TITLE
separate examples dataprocess versus model test

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#20]
Can we think to split the dataprocess and model in tests ?

that would make the toolkit more flexible.

**Comment by PatReis** [comment]
That is a very good idea, infact I am working on the dataprocess next. Can you elaborate on what you mean exactly?

**Comment by thegodone** [comment]
Hello, I check your recent results and it's very encouraging between PAINN / DimenetPP: 
![image](https://user-images.githubusercontent.com/1186658/135711625-b5371bd0-8463-49b5-9f7a-d12ee4cd5a84.png)

**Comment by thegodone** [comment]
Can you add a case for a local file process please, anyone example you can try (ESOL but local file used instead of URL download) please ?

**Comment by thegodone** [comment]
I add a PR for my last question

**Comment by PatReis** [comment]
Hallo, I reworked the inheritance of the data classes. You can now always use the classes in kgcnn.data without any download or folder restriction. Only the kgcnn.data.datasets inherit from DownloadDataset. I put an example jupyter notebook in notebooks.
