### ISSUE TITLE
Distributed training support

### ISSUE THREAD

**Issue by segermans** [aimat-lab/gcnn_keras#22]
Hi! 

Thanks for providing this library. It helps a great deal in working with graphs in Tensorflow.

I have the following issue: I want to perform distributed training using multiple GPUs (using MirroredStrategy). However, the KGCNN layers seem to give problems here when loading a trained model for testing. An illustration with the exact error is provided below. Although I believe you are aware of this issue (it is also indicated in the 'limitations' section of your paper), do you know how to circumvent this? 

Thanks in advance. Cheers, Seger
![image](https://user-images.githubusercontent.com/61347384/130927505-b3cdd407-8cbd-4a10-9991-69182d9c8b1f.png)

**Comment by PatReis** [comment]
Hey,
thanks for checking out our repo. I have not tested yet the different distrubted training strategies within tf.keras.
I will try to look into parallel training in the future (however there are some other things I want to improve and add to kgcnn first).
Nonetheless, I think the error may not be necessarily related to the distribution itself but a problem with the custom activation layers and serialization. I wanted to make the leak and beta-parameters learnable but that somehow causes problems with loading and saving models. I changed it back to be static in the latest commit.

Recently, I have reworked the datasets and training scripts and parts of the models, which may have caused some new bugs. Sorry for that. But I think that having fewer trainig scripts and storing the results helps in using kgcnn on the long run. I will focus on not changing the interfaces and keeping the names from 1.1.0 onwards.

Hopefully, I have a stable version 1.1.0 soon to push to pip.
Is it possible to pull the lates git-version and try again?

Best, Patrick

**Comment by PatReis** [comment]
Hey,
I tested distributed training with `tf.keras` for the latest version and it worked fine for me. However, to see a speed-up you need to go to larger batch-sizes or more expensive GPU load.

I would close the issue. Feel free to open it again if you encounter problems.
I may add distribution strategy to default training scripts in the future.
