### ISSUE TITLE
DMPNN implementation

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#23]
can you implement the Direct MPNN (bond propagation instead of Atom propagation) ?

https://github.com/sxxgrc/molecule-restaurant/blob/d7dfb1cd35ab7729708369c7509111b9b4385054/prediction_model/models/directed_mpnn.py#L11

https://pubs.acs.org/doi/abs/10.1021/acs.jcim.9b00237

https://github.com/chemprop/chemprop

thanks in advance,

GG

**Comment by PatReis** [comment]
I have added a DMPNN implementation and it is suprisingly good on Lipo dataset. However, I have not yet added the property distribution featurization.

**Comment by thegodone** [comment]
I don't think we need this part of the feature for the moment. it can be added in the Future
