### ISSUE TITLE
return the idx of the failed molecule processed ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#32]
Can we know which molecules failed during the dataprocess ?

**Comment by PatReis** [comment]
Yes, I will try to add it when redoing the mol generation.

**Comment by thegodone** [comment]
The idea is to be able to plug labels not from the molecule reader but with an optional pandas reader and filter the rows that failed in the reader process. Also with this method that will be much easier to select the target label you want independently of the molecule process.

**Comment by PatReis** [comment]
I updated the class and they will be added after reading in self.valid_molecule_id

**Comment by PatReis** [comment]
So you could simply do something

labels[np.array(dataset.valid_molecule_id, dtype="int")]

**Comment by thegodone** [comment]
thanks

**Comment by PatReis** [comment]
I think I will try to find a better solution.

**Comment by thegodone** [comment]
Ok i see. Did you have Time to look on the issue on régressions exemples for Esol we already exposed 4 models in OCHEM. Would be Nice to have more.


Envoyé de mon iPhone

**Comment by PatReis** [comment]
I thought about having also empty nodes and edges added and then maybe write a dataset.clean() method for all datasets that removes empty graphs (or optionally unconnected nodes) and also could print out automatic statistics.

**Comment by PatReis** [comment]
The dataset can have None or incomplete graphs. You can now run `clean(["edge_indices"])` with a list of properties or features one needs for the model.
