### ISSUE TITLE
can we have example for ESOL of all literature models

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#34]
that would be nice to have the "default model hyper" for regression for:

- [x] GAT
- [x] GATv2
- [x] GraphSAGE
- [x] Megnet
- [x] Schnet
- [x] DimenetPP
- [x] NMPN
- [x] GCN

**Comment by thegodone** [comment]
Nice to see the progress did you now when the last 3 will be ready ?

**Comment by PatReis** [comment]
I will just check the NMPN implementation again with the original repo as it still does not reach chemical accuracy on qm9.

**Comment by PatReis** [comment]
Okay, I have reworked the NMPN implementation. It should be closer to the original implementation now. I also ran the training.

**Comment by thegodone** [comment]
I will test MNPN today thanks great job!
