### ISSUE TITLE
this commit eb5b8d8 breaks DMPNN model

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#35]
After moving to commit eb5b8d8 got the following error running DMPNN model:

ValueError: Shape must be at least rank 2 but is rank 1 for '{{node model/dmpnnp_pooling_edges_directed/dmpnn_gather_edges_pairs/gather_nodes_ingoing/GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT64, batch_dims=0](model/dmpnnp_pooling_edges_directed/dmpnn_gather_edges_pairs/gather_nodes_ingoing/PartitionedCall, model/dmpnnp_pooling_edges_directed/dmpnn_gather_edges_pairs/gather_nodes_ingoing/GatherV2/indices, model/dmpnnp_pooling_edges_directed/dmpnn_gather_edges_pairs/gather_nodes_ingoing/GatherV2/axis)' with input shapes: [?], [], [] and with computed input tensors: input[2] = <1>.

it works at commit 5fed55c

**Comment by PatReis** [comment]
Yes, sorry, should be fixed now.

**Comment by thegodone** [comment]
thanks it works
