### ISSUE TITLE
Generation of an Attribute Error on model prediction

### ISSUE THREAD

**Issue by alphonus** [aimat-lab/gcnn_keras#36]
In the model prediction step (I use it in a DQN model so fitting happens later) I get following error:

```
AttributeError: in user code:

    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1478 predict_function  *
        return step_function(self, iterator)
    /opt/conda/lib/python3.7/site-packages/kgcnn/layers/pool/pooling.py:46 call  *
        nod, node_part = dyn_inputs[0].values, dyn_inputs[0].row_splits

    AttributeError: 'Tensor' object has no attribute 'values'
```

I'm running Python version 3.7, TF Version 2.4.1, kgcnn 1.1.1.
The model code :

```
    s = 12 #Board size
     n = keras.Input(shape=(None, 2), name='node_input', dtype="float32", ragged=True)
    ei = keras.Input(shape=(None, 2), name='edge_index_input', dtype="int64", ragged=True)
    n_in_out = GatherNodes()([n, ei])
    node_messages = Dense(10, activation='relu')(n_in_out)
    node_updates = PoolingLocalMessages()([n, node_messages, ei])
    n_node_updates = Concatenate(axis=-1)([n, node_updates])
    n_embedd = Dense(s**2)(n_node_updates)
    g_embedd = PoolingNodes()(n_embedd)

    inputs = keras.Input(shape=(s,s,16))#,name = 'The game map'
    f = layers.Flatten()(inputs)   
    h,w= s,s
    f = layers.Dense(w*h,activation = "sigmoid")(f)
    f = layers.Reshape((h,w,-1))(f)
    combined = layers.Concatenate()([f, layers.Reshape((h,w,-1))(g_embedd)])
    #cov_combined = layers.Conv2D(4, 2, activation='relu', data_format='channels_last')(combined)
    #cov_combined = layers.Dense(1)(combined)
    units = layers.Dense(6,activation = "softmax")(combined)#,name = "Units_actions"
    cities = layers.Dense(2,activation = "sigmoid")(combined)#,name = "Cities_actions"
    output = layers.Concatenate()([units,cities])
    model = keras.Model(inputs = [n, ei, inputs], outputs = output)
    model.compile(optimizer= "adam", loss= custom_mean_squared_error ,metrics = ["accuracy"])
```

**Comment by PatReis** [comment]
Hallo,
so the error manly says that the pooling layer expects a ragged tensor but got a normal tensor. I have not yet made the pooling layer accept normal tensors as well. Gather should accept both. 

In the latest git version, you should get an assert error with a more reasonable error message. Just for the record, I moved the pooling.py into layers. So you would use PoolingLocalMessage from kgcnn.layers.pooling import ...

If your network only has one graph, you would not need a ragged tensor but some layers only work for ragged at the moment. The input layer says ragged=True. Did you check the shape of n? It should be (batch, None, 2). If n is a tensor of lets say shape (1, 50, 2) this could be the reason for the error (50 is just an example). You would simply cast this into `tf.RaggedTensor.from_row_lengths(n[0], tf.constant([50]))`

If that does not help, you would have to send more code with simple data as input.

**Comment by alphonus** [comment]
Ok, i missread that I needed to convert the arrays (I used Numpy Arrays as input, as I could not get a tf.Dataset working) using 
`edge_list = tf.ragged.constant(edge_list, ragged_rank=1, inner_shape=(2, ))`

I feel a lot more stupid now

**Comment by PatReis** [comment]
no problem. If you have a list of numpy arrays, where each array is a graph list like node attributes or edge indices, you can convert this into a ragged tensor faster than `tf.ragged.constant` with `kgcnn.utils.data.ragged_tensor_from_nested_numpy`.
The ragged tensor should not be moved to the GPU if you create it. Only when indexing/operating (as it is done by `keras.fit`), tensorflow moves the batches to the GPU. 
We are actually looking into a fast loading option within `tf.Dataset` at the moment.

If it works for you, feel free to close the issue. If you want to discuss more, you can always start a discussion under the discussions tab.
