### ISSUE TITLE
Megnet & NMPN error using Custom dataset

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#37]
Traceback (most recent call last):
  File "GCN-keras.py", line 213, in <module>
    dataloader = NumpyTensorList(*[getattr(dataset, x['name']) for x in hyper['model']['inputs']])
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/io/loader.py", line 34, in __init__
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/io/loader.py", line 37, in _length_test
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/io/loader.py", line 37, in <listcomp>
TypeError: object of type 'NoneType' has no len()

I use the last version of the code 1.1.2 Master bug got an error.

I don't see this error with GraphSage, GAT, GATv2 models parameter

**Comment by thegodone** [comment]
my mistake

**Comment by thegodone** [comment]
I use this data preparation script

![image](https://user-images.githubusercontent.com/1186658/144257375-21fd703f-9346-4d3f-ac1a-883519f5a62d.png)

**Comment by PatReis** [comment]
The error means that the name of the input layer does not have a property set in the dataset. For DimeNetPP it is angle_indices for sure. so you also need
`dataset.set_angle()`
But I should write something to that also the name is printed in the error message, otherwise we would not know what it was...

**Comment by PatReis** [comment]
ah for GCN its edge_weights I guess
the can be set for the dataset via `normalize_edge_weights_sym()`

**Comment by thegodone** [comment]
Great thanks 

Envoyé de mon iPhone

**Comment by PatReis** [comment]
for megnet it is probably the `graph_number` but that can be replaces with `graph_attributes`. MegNet needs a graph tensor as state or graph input feature.

**Comment by thegodone** [comment]
Thanks for the tips, I was able to run GCN and DimenetPP models now. But I still don't know what to do with the Megnet  code.  Cause I don't see in the repo where to set the graph_attributes in the features of my custom dataset.

**Comment by PatReis** [comment]
oh sorry, I meant in the hyper parameters for input there is 
`"inputs": [
                {"shape": [None], "name": "node_number", "dtype": "float32", "ragged": True},
                {"shape": [None, 3], "name": "node_coordinates", "dtype": "float32", "ragged": True},
                {"shape": [None, 2], "name": "range_indices", "dtype": "int64", "ragged": True},
                {"shape": [2], "name": "graph_attributes", "dtype": "float32", "ragged": False}
            ],`
And when there is a not a `graph_attributes` then this could be a problem.

**Comment by thegodone** [comment]
I see but can we make them on the fly i see that it is mw só not difficult to add a dataset.set_graph_attribute(mw) ?

Envoyé de mon iPhone

**Comment by thegodone** [comment]
I remove graph_attributes part from the hyper json but got another error
![image](https://user-images.githubusercontent.com/1186658/144566570-8807611f-66e4-4297-9450-89dee3b0cbf6.png)

my settings: 

![image](https://user-images.githubusercontent.com/1186658/144566614-1c54c6e6-7f50-493b-ac4e-1362f2a1b711.png)

![image](https://user-images.githubusercontent.com/1186658/144566715-7a770858-70d7-4c9b-8be2-e8ec8817f390.png)

**Comment by PatReis** [comment]
No No sorry, you can not remove it. MegNet needs graph attributes. I meant if in place of graph_attributes there is something like graph_size or graph_number (which is not set, then there will be a Problem.) But graph_attributes should be set automatically.

**Comment by PatReis** [comment]
Can you put this before the dataloader part?
`for x in hyper['model']['inputs']:
    if not hasattr(dataset, x['name']):
        print("ERROR: Dataset does not has information on %s" % x['name'])`

**Comment by PatReis** [comment]
I will make a method to the dataset base class like `process_hyper`

**Comment by thegodone** [comment]
this is really an excellent idea to avoid mistake between data process and architectude needs dependencies.

**Comment by thegodone** [comment]
by using this part in the "json":
{"shape": [2], "name": "graph_attributes", "dtype": "float32", "ragged": False} 
fix the issue
