### ISSUE TITLE
how to change the number of output from 1 to N for DimeNetPP

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#38]
is this is the "num_targets": 1 it the right value in other methods we have the output_mlp

**Comment by PatReis** [comment]
Yes, sorry, DimeNet in the original implementation does not really have a fixed MLP at the output. But I could add one to make it consistent.
So num_targets will determine the output. Yes.

**Comment by thegodone** [comment]
That would be Nice

Envoyé de mon iPhone

**Comment by thegodone** [comment]
Is it possible also to have linear or sigmoïde activation layer output ?

Envoyé de mon iPhone

**Comment by PatReis** [comment]
I have added an output MLP to DimeNetPP which per default is None (to keep the original implementation), in the `hyper_esol.py`, I have added it and used it for regression. So you should be able to change the number of ouputs and output activation function. But note that DimeNetPP need geometric information and does not scale very well to larger molecules. I want to add MXMNet in the near future that fixed some problems of DimeNet.

**Comment by PatReis** [comment]
So you should be able to change the last activation function from linear to sigmoid in the version using a MLP at the output (latest hyper-parameters in hyper_esol.py).
