### ISSUE TITLE
bug with last commit on mac

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#40]
This is a nice idea to parallelize the rdkit process but it's not trivial to be cross-platform compatible
training
INFO:kgcnn: Generating molecules and store train.sdf to disk...
Traceback (most recent call last):
  File "/Users/tgg/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/mol/gen/default.py", line 2, in <module>
    import rdkit
  File "/Users/tgg/rdkit2021/rdkit/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: dlopen(/Users/tgg/rdkit2021/rdkit/rdkit/rdBase.so, 2): Library not loaded: @rpath/libboost_python38.dylib
  Referenced from: /Users/tgg/rdkit2021/rdkit/rdkit/rdBase.so
  Reason: image not found
Traceback (most recent call last):
  File "AttFPX-keras.py", line 183, in <module>
    dataset.prepare_data(overwrite=True, smiles_column_name="smiles", make_conformers=False)
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/data/moleculenet.py", line 100, in prepare_data
    mb = self._smiles_to_mol_list(smiles, add_hydrogen=add_hydrogen, sanitize=True,
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/data/moleculenet.py", line 67, in _smiles_to_mol_list
    mg = smile_to_mol(smiles[i:i+1000], self.data_directory,
  File "/Users/itetko/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/mol/gen/base.py", line 73, in smile_to_mol
    raise ValueError("Batch process returned with error:", return_code)
ValueError: ('Batch process returned with error:', CompletedProcess(args=['python3', '/Users/tgg/anaconda3/lib/python3.8/site-packages/kgcnn-1.1.2-py3.8.egg/kgcnn/mol/gen/default.py', '--file', 'ac079a80-7b72-4d4d-8add-0faeb96456d9.smile', '--nprocs', '12', '--sanitize', 'True', '--add_hydrogen', 'True', '--make_conformers', 'False', '--optimize_conformer', 'True'], returncode=1))

I would suggest to make something like this : 

```
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

# if you have to make a list conversion
smis = [smi for smi in SMILES]


# need to be adapt to your code
def getSmilesToMol(smi):
    try:
        return ...
    except:
        return Null

with ThreadPoolExecutor(max_workers=12) as pool:
    res = list(tqdm(pool.map(getSmiles,smis),total=len(smis)))
```
We need to find a way to get the parameters but it's less complicated than to run "command line"

guillaume

**Comment by PatReis** [comment]
Oh I see. Okay, I change it into ThreadPoolExecuter or Ray for the default. I have the default to use rdkit and openbabel as fall-back and it works quite nice. I wanted to use the command line execution to easily put in ballon (or anything similar) for conversion.

**Comment by thegodone** [comment]
I think Balloon is less sensitive than RDKit for the command line. I think you can use the command line for Balloon case only.

**Comment by thegodone** [comment]
working now thanks more stable
