### ISSUE TITLE
pickle dataset object

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#46]
is there a way to save pickle of the dataset object for a very long dataset ?

![image](https://user-images.githubusercontent.com/1186658/162725373-bba13cd8-66ef-46a2-bad4-8f249b89377e.png)

**Comment by PatReis** [comment]
Hallo,
yes, the dataset should have a `dataset.save()` method which stores a pickle of the dataset. 
One should also be able to `dataset.load()`.
You can also load the pickle manually, which should be a list of dicts. 
I added the save example to `[tutorial_custom_moleculenet.ipynb](https://github.com/aimat-lab/gcnn_keras/blob/master/notebooks/tutorial_custom_moleculenet.ipynb)`

**Comment by thegodone** [comment]
thanks
