### ISSUE TITLE
implementation of MAT graph

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#48]
could it be possible to implement this code / paper:

- https://github.com/ardigen/MAT. https://arxiv.org/abs/2002.08264
- https://github.com/lucidrains/molecule-attention-transformer (I think this code is clearer and cleaner)

**Comment by PatReis** [comment]
Hallo, sorry for the long absence.
I will have a look at it. I still want to work on HamNet a little bit, but I fear I will not be able to make the encoder part of HamNet to work within tensorflow quickly. 
Then I will try out MAT.
