### ISSUE TITLE
how to change only Labels in a saved dataset ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#49]
I wonder if we can modify the Labels in a large saved dataset pickle file ?

**Comment by PatReis** [comment]
Hallo, sorry for the long absence.
At the moment the only way I see it would be to load it from disk like:
`ds =  MemoryGraphList()
ds.load("filapth/datasetname.pickle")
`
and then simply change the labels you want. Just note that you should do all this before running e.g. `ds.clean`
`
ds[101].assign_property("graph_label", 10.2)
`
you can if you want manually add the ID of the graph:
`
for i in range(len(ds)):
    ds[i].assign_property("manual_id", i)
`

**Comment by thegodone** [comment]
works perfectly, exactly what i was looking for!
