### ISSUE TITLE
How to handle salt and mixture of smiles

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#51]
I see few cases (marginal but real cases) where you have a salt for example in smiles mixture as input. the issue is that during the data preparation we have a crash cause the "Adj" matrice is not inversible (I guess). Can we put an exception in this case and just set invalid instead of a breaking point ?

**Comment by PatReis** [comment]
We can adjust for this case. Can you put an error message to see where it crashes? Some models may have problems with this case which may not be possible to fix but in general unconnected nodes should be working.

**Comment by thegodone** [comment]
look like it's AttFP related only I am checked for an example

**Comment by PatReis** [comment]
Any update? I am about to improve the features in `kgcnn.mol`...

**Comment by thegodone** [comment]
I Will speed time on it with l’as version 2.0.4 next week

**Comment by thegodone** [comment]
#
