### ISSUE TITLE
implementation GINE the Edge extension of GIN

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#52]
That would be interesting to add the Edge compatible version of GIN:

https://arxiv.org/abs/1905.12265

it's implemented in PYG &  dgl
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/gin_conv.html#GINEConv
https://docs.dgl.ai/en/latest/generated/dgl.nn.pytorch.conv.GINEConv.html

**Comment by PatReis** [comment]
Hey, I added a `GINE` to `gin_conv` and also an additional `make_model_edge` variant but did not tested it yet. 
To learn on node classification or regression, I might have to add a custom loss or check again with latest tf.version.

**Comment by thegodone** [comment]
Thanks GINE code works on my case. 
I have my own losses / metrices not defined in json parameters more convenient for me.
