### ISSUE TITLE
how to read directly 3D from a sdf file

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#59]
Is there a way to read directly my 3D molecules coordinates structure "mol" rdkit object (based on corina or ballon) from a given sdf file and my targets coming from a given csv file together ?

maybe something like this can be used 

from rdkit.Chem import PandasTools
fn = 'file.sdf'
df = PandasTools.LoadSDF(fn, embedProps=True, molColName=None)

indeed would be nice to be able to convert pandas df mols into graphs

**Comment by PatReis** [comment]
So what should be possible if you have named them identical like `file.csv` and `file.sdf` and you put them in the same folder `Folder` you can make a `MoleculeNetDataset(data_directory="/Folder", file_name="file.csv", dataset_name="Dataset")` ontop. Just call `read_in_memory` directly or `prepare_data(overwrite=False)` to skip SDF file generation.

**Comment by PatReis** [comment]
Otherwise I can add a `from_sdf_file()` to `MolecularGraphRDKit` if you want, but you would have to set up the dataset manually.  `MolecularGraphRDKit`  is the interface to expose graph properties from a rdkit mol object.

**Comment by thegodone** [comment]
To clarify, I receive ochem molecule as 3d file cause SYSTEM as a farm computer distributed plus a store of molecule 3d is already seen. So my wish is to be able get this process link to rdkit custom featuring for graph. So from_sdf_file looks good. But i cannot get from ochem targets on this sdf file i need to read a second file for targets.


Envoyé de mon iPhone

**Comment by PatReis** [comment]
Okay, so I understand better now, I think. The current dataset classes are all `MemoryGraphDataset`s so the dataset must fit into memory, we have plans and code fragments for Loaders and tf.Dataset readers that can access some sort of database and load training data on the fly but that is still on the TODO-List. For `MemoryGraphDataset` it is simply easier to load one file once. But we have the `file_dicrectory` property so I can add functionality to (beside of smiles) also have a column "file_names" in the `file.csv` that collects the single 3D files (without generating structures) and stores them into a single .sdf file. Note that you would have to run `prepare_data(overwrite=True)` if you add mol-files in the file_directory.

Regarding the rdkit custom featuring for graph, the `MoleculeNetDataset.set_attributes` should be fully customizable. With setting functions in place of string arguments, a custom_callback and I will also add a custom_transform parameter that can modify the molecule before graph extraction.

**Comment by thegodone** [comment]
Indeed all molecules are preprocessed and delivered in one unique SDF file containing all the molecules by OCHEM as well as a csv file that contains the "targets" & "smiles" line by line. the only issue it may happens that few smiles can be not reconigned by RDkit so my only issue is the alignement of SDF entries and valid smiles.

**Comment by thegodone** [comment]
I try method 1: overwrite=False

![image](https://user-images.githubusercontent.com/1186658/182611583-7da4b3d7-0639-4e63-8d12-7422d768ca8c.png)

**Comment by PatReis** [comment]
Hey, I can not really tell from the error log if I have not seen the SDF file, but assuming there was one molecule without conformer, and running map before clean, coud lead to this error. I changed the return behaviour of `node_coordinates`. 
Can you check again with latest git verison, otherwise you may have to send me the SDF plus CSV file.

**Comment by PatReis** [comment]
Hey, I tested it with and it worked fine for me. 
`from kgcnn.data.moleculenet import MoleculeNetDataset

dataset = MoleculeNetDataset(data_directory="Archive", file_name="train.csv")
dataset.prepare_data(overwrite=False)
dataset.read_in_memory(label_column_name="Result0")
dataset.set_attributes()
dataset.map_list(method="set_range", max_distance=4)`

**Comment by thegodone** [comment]
Working m!

**Comment by thegodone** [comment]
I have another error for DimenetPP
![image](https://user-images.githubusercontent.com/1186658/187209145-e1d5ae33-d315-445f-bd48-36a06a821d70.png)

code basically

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/1186658/187209245-b1cae094-51a0-4888-bfac-90106cacd26a.png">

**Comment by thegodone** [comment]
Are you sure you keep the setting from 21 days ago in the last versions ?
can you show me what you change I cannot find the proper commit
