### ISSUE TITLE
Adding External Descriptors to DMPNN

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#70]
Can you add an option to add csv descriptors (Molecules plain vector) to DMPNN ?

similar to this 

![image](https://user-images.githubusercontent.com/1186658/187175755-a6371096-9c0c-4a1c-8053-9e940e2390e3.png)

Cause OCHEM produce those type of molecular descriptors I propose to do the version loading from the csv files containing smiles and targets the rest of "Descriptors".

Would be useful to call them Desc0,Desc1, etc... like in OCHEM and be able to plug them by concatenation to the graph feature before the MLP layer like in the chemprop tool.

thanks

**Comment by PatReis** [comment]
Hallo,
I added a graph state for DMPNN as you described, with hyper-parameter `{"use_graph_state": True}`.
To generate a graph state from descriptors you can use the additional_callback function where you get the csv-line and the `MolGraphInterface` object.
```python
def descriptor_callback (mg, ds):
    return np.array([ds["Desc0"], ds["Desc1"]])

dts.set_attributes(
    additional_callbacks= {"graph_desc": descriptor_callback},
)
```
note that you then have to use this name then in inputs:
```python
model(inputs=[
                    {"shape": [None, 41], "name": "node_attributes", "dtype": "float32", "ragged": True},
                    {"shape": [None, 11], "name": "edge_attributes", "dtype": "float32", "ragged": True},
                    {"shape": [None, 2], "name": "edge_indices", "dtype": "int64", "ragged": True},
                    {"shape": [None, 1], "name": "edge_indices_reverse", "dtype": "int64", "ragged": True},
                    {"shape": [20], "name": "graph_desc", "dtype": "float32", "ragged": False}]
)
```

**Comment by thegodone** [comment]
wonderful thanks a lot I will test

**Comment by thegodone** [comment]
I did this to make it flexible dynamic to descs size:
     return np.array(ds[descs],dtype='float32')
