### ISSUE TITLE
internal versus external 3D SDF molecule CIP issue

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#71]
Messages from:
Internal 3d
INFO:kgcnn.mol.encoder:OneHotEncoder Symbol found ['Cl', 'C', 'Br', 'O', 'N', 'P', 'S']
INFO:kgcnn.mol.encoder:OneHotEncoder Hybridization found [rdkit.Chem.rdchem.HybridizationType.SP3, rdkit.Chem.rdchem.HybridizationType.SP2, rdkit.Chem.rdchem.HybridizationType.SP]
INFO:kgcnn.mol.encoder:OneHotEncoder TotalDegree found [1, 4, 3, 2]
INFO:kgcnn.mol.encoder:OneHotEncoder TotalNumHs found [0, 2, 1, 3]
**INFO:kgcnn.mol.encoder:OneHotEncoder CIPCode found [None]**
INFO:kgcnn.mol.encoder:OneHotEncoder ChiralityPossible found [None, '1']

External 3D
INFO:kgcnn.mol.encoder:OneHotEncoder Symbol found ['Cl', 'C', 'O', 'P', 'S', 'N', 'Br']
INFO:kgcnn.mol.encoder:OneHotEncoder Hybridization found [rdkit.Chem.rdchem.HybridizationType.SP3, rdkit.Chem.rdchem.HybridizationType.SP2, rdkit.Chem.rdchem.HybridizationType.SP]
INFO:kgcnn.mol.encoder:OneHotEncoder TotalDegree found [1, 4, 3, 2]
INFO:kgcnn.mol.encoder:OneHotEncoder TotalNumHs found [0, 2, 3, 1]
**INFO:kgcnn.mol.encoder:OneHotEncoder CIPCode found [None, 'S', 'R']**
INFO:kgcnn.mol.encoder:OneHotEncoder ChiralityPossible found [None, '1']

I've also observed that the CIP did not provide same response with internal / external 3D dataset.

do you know what it's like this ?

**Comment by thegodone** [comment]
![image](https://user-images.githubusercontent.com/1186658/187371930-f43d32c8-f237-43bb-a017-99abf786a418.png)

we need to run more cases but we use 4 different sources of 3D (first line is RDKit)

**Comment by PatReis** [comment]
Sure it is not the other way round? I will look into it. I also wanted to add a compute_charges option.

**Comment by PatReis** [comment]
I am trying to improve the mol-interface and conversion methods. Can you send me the smiles list to reproduce this?

**Comment by PatReis** [comment]
I am not really sure about this part. As it is now:
```python
m = rdkit.Chem.MolFromSmiles(smile)
# rdkit.Chem.RemoveStereochemistry(m)
if sanitize:
    rdkit.Chem.SanitizeMol(m)
if add_hydrogen:
    m = rdkit.Chem.AddHs(m)
m.SetProp("_Name", smile.strip())
if make_conformers:
    rdkit.Chem.AllChem.EmbedMolecule(m, useRandomCoords=True)
if optimize_conformer and make_conformers:
    rdkit.Chem.AllChem.MMFFOptimizeMolecule(m)
    rdkit.Chem.AssignAtomChiralTagsFromStructure(m)
    rdkit.Chem.AssignStereochemistryFrom3D(m)
rdkit.Chem.AssignStereochemistry(m)
```

**Comment by thegodone** [comment]
Ok the issue is that you need for stability of 3D to addHs during the Embedding and the MMFF optimization step and remove Hs after. 

but this is only fix few cases. We always have molecules that can failed the procedure.

I would do something like this

```
m = rdkit.Chem.MolFromSmiles(smile)
# rdkit.Chem.RemoveStereochemistry(m)
if sanitize:
    rdkit.Chem.SanitizeMol(m)

m.SetProp("_Name", smile.strip())
if make_conformers:
    if add_hydrogen:
        m = rdkit.Chem.AddHs(m)
    rdkit.Chem.AllChem.EmbedMolecule(m, useRandomCoords=True)
    if optimize_conformer:
    rdkit.Chem.AllChem.MMFFOptimizeMolecule(m)
    rdkit.Chem.AssignAtomChiralTagsFromStructure(m)
    rdkit.Chem.AssignStereochemistryFrom3D(m)
    if not add_hydrogen:
        m = rdkit.Chem.RemoveHs(m)

else:
    if add_hydrogen:
        m = rdkit.Chem.AddHs(m)

rdkit.Chem.AssignStereochemistry(m)
```

**Comment by thegodone** [comment]
to avoid try catch you can also check if the Embeding step work so the function return correct validation
```
success = rdkit.Chem.AllChem.EmbedMolecule(m, useRandomCoords=True)
if success == -1:
            raise Exception("Embedding failed!")
```

**Comment by PatReis** [comment]
Okay, thanks, I updated the `kgcnn.mol.convert` function. Does this help to solve your issue from above?
