### ISSUE TITLE
GCN labels

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#78]
Can you clarify model_default terms used in GCN litterature code ?

![image](https://user-images.githubusercontent.com/1186658/189856042-0a9a1d44-e920-4ffb-a87b-afedc757f0c5.png)

I saw edge_attributes here, but edge_weights is used elsewhere.

**Comment by PatReis** [comment]
Yes we had attributes there once, but that was a modification to GCN, not the original GCN, so that is why we changed it.
I renamed the defaults accordingly.
