### ISSUE TITLE
is GAT loop correct ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#79]
![image](https://user-images.githubusercontent.com/1186658/189931704-f5f7fe61-efa7-42e2-9e92-542f935547ed.png)

I see that you use "n" in the loop of each "Attentions". should it not be nk ?

BTW, code is correct in GATv2 version

**Comment by thegodone** [comment]
see pull request #80

**Comment by PatReis** [comment]
accepted pull request.
