### ISSUE TITLE
adding self loop in adj dense matrix

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#89]
can you add an option to do np.eyes(mol.GetNumAtoms()) for the dense adjacency matrix please ?

Depending of the source they put the diagonal to one or zeros depending of the toolkit for MAT

**Comment by PatReis** [comment]
I could add it to the model. For preprocessing, you can already do this like so:
```python
        "data": {
            "dataset": {
                "class_name": "ESOLDataset",
                "module_name": "kgcnn.data.datasets.ESOLDataset",
                "config": {},
                "methods": [
                    {"set_attributes": {}},
                    {"map_list": {"method": "add_edge_self_loops"}},
                    {"map_list": {"method": "set_edge_weights_uniform"}},
                    {"map_list": {"method": "pad_property", "key": "node_number", "pad_width": [0, 1]}},
                    {"map_list": {"method": "pad_property", "key": "node_coordinates", "pad_width": [[0, 1], [0, 0]]}}
                ]
            },
            "data_unit": "mol/L"
        },
```

**Comment by thegodone** [comment]
If it improves the model on Esol we can add it yes or as an option.

Envoyé de mon iPhone

**Comment by PatReis** [comment]
No, I mean, you can already add self-loops in preprocssessing as shown above via: ` {"map_list": {"method": "add_edge_self_loops"}}`.

But anyway I added an option in MAT to add identity to graph adjacency.
