### ISSUE TITLE
need to remove Hs, and a specific single atom molecule case in ESOl dataset

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#9]
AttentiveFP cannot work with single atom molecule. The original code does not include Hs. We can remove from the dataset this case to avoid "C" smile case:

![image](https://user-images.githubusercontent.com/1186658/123090140-17529300-d428-11eb-88a5-d17030d83908.png)

and 

![image](https://user-images.githubusercontent.com/1186658/123090300-45d06e00-d428-11eb-9337-fd6964ddf7d6.png)

**Comment by PatReis** [comment]
Okay, I made the dataset for ESOL as close to the original paper as possible. That means remove the H's and the isolated Carbon atom.
